NBA/urls.py
from django.urls import path
from .views import (
    PlayerList,
    PlayerDetail,
    BasketballPlayerList,
    BasketballPlayerDetail,
    NBAPlayerList,
    NBAPlayerDetail,
)

urlpatterns = [
    path('players/', PlayerList.as_view(), name='player-list'),
    path('players/<int:pk>/', PlayerDetail.as_view(), name='player-detail'),
    path('basketball-players/', BasketballPlayerList.as_view(), name='basketballplayer-list'),
    path('basketball-players/<int:pk>/', BasketballPlayerDetail.as_view(), name='basketballplayer-detail'),
    path('nba-players/', NBAPlayerList.as_view(), name='nbaplayer-list'),
    path('nba-players/<int:pk>/', NBAPlayerDetail.as_view(), name='nbaplayer-detail'),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include

# urls configuration for images
from django.conf.urls.static import static
from django.conf import settings

# for JWT 
# from rest_framework_simplejwt.views import (
#     TokenObtainPairView,
#     TokenRefreshView
# )
# from rest_framework_simplejwt import views as jwt_views

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', include('api.urls')),

    path('', include('apiJWT.urls')),

    path('', include('NBA.urls')),
    
    path('', include('store.urls')),
    
    path('randomObject/', include('randomObject.urls')),

    path('ckeditor/', include('ckeditor_uploader.urls')),

    # path('api/token/',TokenObtainPairView.as_view(),name='token_object_pair'),
    # path('api/token/refresh/',TokenRefreshView.as_view(),name='token_refresh'),
]

# urls configuration for images
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views
# from store.views import registerPage, verify_email

app_name='store'


urlpatterns = [
    path('', views.store, name="store"),

    # to make staff

    path('make-staff/', views.make_users_staff, name='make-staff'),

    # for email verification

    # path('verify-email/<int:user_id>/<str:token>/', views.verify_email, name='verify_email'),


# for admin dashboard

    # path('adminDashboard2/', views.AboutView.as_view(), name="adminDashboard2"),

    path('adminDashboard2/', views.adminDashboard, name="adminDashboard2"),


    path('adminPage/', views.adminPage, name="adminPage"),


# for user
    path('login/', views.loginPage, name="login"),
    path('logout/', views.logoutUser, name="logout"),
    path('register/', views.registerPage, name="register"),

    # path('verify_email/<int:user_id>/<str:token>/', verify_email, name='verify_email'),

    path('profile<int:pk>/', views.userProfile, name="user-profile"),
    path('update-user/<int:pk>/', views.updateUser, name="update-user"),
    path('deleteUser/<str:pk>/', views.deleteUser, name="deleteUser"),



    path('product/<int:pk>', views.ProductPage.as_view(), name="productPage"),  #.as_view() 

# CRUD for product

    path('createProduct/', views.createProduct, name="createProduct"),
    path('updateProduct/<str:pk>/', views.updateProduct,name="updateProduct"),
    path('deleteProduct/<str:pk>/', views.deleteProduct, name="deleteProduct"),

# Cart and Checkout views

    path('cart/', views.cart, name="cart"),
    path('checkout/', views.checkout, name="checkout"),

    path('update_item/', views.updateItem, name="update_item"),
    
    path('process_order/', views.processOrder, name="process_order"),
]
 

store/forms.py
from django.forms import ModelForm

from .models import Product, Customer, OrderItem

from django.contrib.auth.models import User

class UserForm(ModelForm):
    class Meta:
        model = Customer
        fields = ['name','email','profile_pic']

class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

class OrderHistoryForm(ModelForm):
    class Meta:
        model = OrderItem
        fields = ['product']

store/views.py
import json
import datetime

from .models import * # * will import all the database models
# from .utils import cookieCart, cartData, guestOrder
from randomObject.models import RandomObject

# for search
from django.db.models import Q

# for class based views
from django.views import View

from django.shortcuts import render, redirect

# for login
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout

#for message
from django.contrib import messages

# from django.conf import settings
# User = settings.AUTH_USER_MODEL

# for email

from django.contrib.auth.models import User
from django.utils.crypto import get_random_string

from django.core.mail import send_mail
from django.urls import reverse

#for userCreationForm
from django.contrib.auth.forms import UserCreationForm

from django.views.generic import TemplateView

from .forms import  UserForm, ProductForm

from django.http import JsonResponse

from .utils import has_customer, send_email

from django.contrib.auth import get_user_model


# setting a user as a staff 

# This line gets the user model from Django's authentication system.
# It assigns it to a variable called User so it can be used later in the code.
User = get_user_model()

# This defines a view function called make_users_staff that takes a request object as an argument.
# The view will handle a POST request that is sent when the user submits a form.
def make_users_staff(request):
	# This checks if the HTTP method used in the request is POST.
	# In this case, it's looking for a form submission.
	if request.method == 'POST':
		# This gets a list of user IDs from the POST data.
		# It's looking for form fields with the name "users" and getting their values.
		# Get the users you want to make staff from the form data
		user_ids = request.POST.getlist('users')
		# This uses the Django ORM to get a queryset of User objects whose IDs match the IDs in user_ids.
		users_to_make_staff = User.objects.filter(id__in=user_ids)

		# Loop through the users and make them staff
		# This loops through the queryset of users and sets their is_staff attribute to True,
		# then saves the changes to the database.
		for user in users_to_make_staff:
			user.is_staff = True
			user.save()
		# This sets a boolean variable success to True.
		# This is used later to determine if the action was successful.	
		success = True
	# If the HTTP method was not POST,
	# it sets success to False and sets users_to_make_staff to an empty queryset.
	else:
		success = False
		users_to_make_staff = User.objects.none()
	# This gets a queryset of all User objects in the database.
	users = User.objects.all()
	# This creates a dictionary called context that contains the
	# users, users_to_make_staff, and success variables.
	# This will be used to pass data to the template.
	context = {
        'users': users,
        'users_to_make_staff': users_to_make_staff,
        'success': success
    }
	return render(request, 'store/make_staff.html', context)

'''
User = get_user_model()

def make_users_staff(request):
    if request.method == 'POST':
        # Get the users you want to make staff from the form data
        user_ids = request.POST.getlist('users')
        users_to_make_staff = User.objects.filter(id__in=user_ids)

        # Loop through the users and make them staff
        for user in users_to_make_staff:
            user.is_staff = True
            user.save()

        return render(request, 'store/make_staff.html', {'success': True})

    users = User.objects.all()
    return render(request, 'store/make_staff.html', {'users': users})
'''



#Admin Dashboard
# class AboutView(TemplateView):
# 	template_name = "store/adminDashboard2.html"

def adminDashboard(request):

	products = Product.objects.all()
	customers = Customer.objects.all()
	randomObjects = RandomObject.objects.all()

	context={
		'products':products,
		'customers':customers,
		'randomObjects':randomObjects,

	}
	return render(request, 'store/adminDashboard2.html', context)


def adminPage(request):
	context={

	}
	return render(request, 'store/adminPage', context)


# views for LOGIN

def loginPage(request):
	page = 'login'
	if request.user.is_authenticated:
		return redirect('store:store')
	if request.method == 'POST':
		username = request.POST.get('username')
		password = request.POST.get('password')
		try:
			user = User.objects.get(username=username)
		except:
			messages.error(request, 'User does not exist')
		user = authenticate(request, username=username, password=password)
	
		if user is not None:
			login(request, user)
			if user.is_superuser:
				return redirect('store:adminDashboard2')
			return redirect('store:store')
		else:
			messages.error(request, 'Username OR password does not exist')
	context={
		'page':page,
	# 'username':username,
	# 'password':password,
  }
	return render(request, 'store/login_register.html', context)




# views for LOGOUT


@login_required(login_url='login')

def logoutUser(request):
	logout(request)
	return redirect('store:store')



# views for REGISTER

# def registerPage(request):
#     page='register'
#     form = UserCreationForm()
#     if request.method == 'POST':
#         form = UserCreationForm(request.POST)
#         if form.is_valid():
#             user = form.save(commit=False)
#             user.username = user.username.lower()

#             user.is_active = False

#             user.save()
#             # customer=Customer(user=user)
			

#             # customer.save()

#             token = get_random_string(length=32)
#             profile = Customer.objects.create(user=user, verification_token=token)

#             verification_url = request.build_absolute_uri(
#             reverse('verify_email', kwargs={'user_id': user.id, 'token': token})
#             )
	
#             send_mail(
#                 'Verify your email',
#                 f'Thank you for registering in the AOIS ( All in one store ). Please click the following link to verify your email: {verification_url}. After your email has been verified, enjoy shopping!!',
#                 'noreply@infodev.com.np',
#                 [user.username],
#                 fail_silently=False,
#             )
			
#             # send_email(user)

#             return redirect('login')
#         else:
#             messages.error(request, 'An error occurred during registration')
#     return render(request, 'store/login_register.html', {'form':form, 'page':page})


def registerPage(request):
	
	page='register'
	form = UserCreationForm()
	if request.method == 'POST':
		form = UserCreationForm(request.POST)
		if form.is_valid():

			user = form.save(commit=False)
			user.username = user.username.lower()

			# user.is_active = False

			user.save()
			c=Customer(user=user)	#
			c.save()	#

			# email verification :


			# token = get_random_string(length=32)

			# profile = Customer.objects.create(user=user, verification_token=token)
			
			# print(profile)

			# verification_url = request.build_absolute_uri(
			# reverse('store:verify_email', kwargs={'user_id': user.id, 'token': token})
			# )
			# send_mail(
			#     'Verify your email',
			#     f'Thank you for registering in the AOIS ( All in one store ). Please click the following link to verify your email: {verification_url}. After your email has been verified, enjoy shopping!!',
			#     'noreply@infodev.com.np',
			#     [user.username],
			#     fail_silently=False,
			# )


			# end of email verification !
			
			send_email(user)
			messages.success(request, 'Your account has been created. Please check your email to verify your account.')
			return redirect('store:login')
		else:
			print(form.errors)
			messages.error(request, 'An error occurred during registration')
	else:
		form = UserCreationForm()  # re-instantiate form if request method is not POST
	return render(request, 'store/login_register.html', {'form':form, 'page':page})



# VERIFY EMAIL

# def verify_email(request, user_id, token):
#     user = User.objects.get(id=user_id)
#     profile = Customer.objects.get(user=user, verification_token=token)
	
#     if profile is not None:
#         user.is_active = True
#         user.save()
#         profile.delete()
		
#         # Log the user in
#         user = authenticate(username=user.username, password=user.password)
#         login(request, user)
		
#         return redirect('login')
#     else:
#         # Handle invalid or expired tokens
#         pass



# views for USERPROFILE

def userProfile(request, pk):
	orderDetail = Order.objects.filter(customer=request.user.customer)
	orderdetails = OrderItem.objects.filter(order__in=orderDetail)
	# product = Product.objects.get(id=pk)
	# order = Order.objects.all()
	# orderItem = OrderItem.objects.all()
	if request.user.is_authenticated:
		try:
			customer = request.user.customer
			order, created = Order.objects.get_or_create(customer=customer, complete=False)
			
			cartItems = order.get_cart_items
		except:
			cartItems = order['get_cart_items']
	else:
		cartItems = order['get_cart_items']

	context = {
		
		'orderDetails': orderdetails,
		'cartItems':cartItems,	
		
		# 'product': product,
		# 'order': order,
		# 'orderItem':orderItem,
	}
	return render(request, 'store/profile.html', context)



# views for UPDATE USER

@login_required(login_url='login')

def updateUser(request, pk):
	user = Customer.objects.get(id=pk) #request.user.customer
	form = UserForm(instance=user)
	if request.method == 'POST':
		form = UserForm(request.POST, request.FILES, instance=user)
		if form.is_valid():
			form.save()
			return redirect('store:user-profile', pk=user.id)
	if request.user.is_authenticated:
		try:
			customer = request.user.customer
			order, created = Order.objects.get_or_create(customer=customer, complete=False)
			
			cartItems = order.get_cart_items
		except:
			cartItems = order['get_cart_items']
	else:
		cartItems = order['get_cart_items']
	
	context = {
		'form':form,

store/templates/store/adminPage.html
{% extends 'store/main.html' %}

{% block content %}

{% load static %}

{% endblock content %}

store/templates/store/cart.html
{% extends 'store/main.html' %}
{% load static %}
{% block content %}
<div class="row">
    <div class="col-lg-12">
        <div class="box-element">
            <a class="btn btn-outline-dark" href="{% url 'store:store' %}">&#x2190; Continue Shopping</a>
            <br>
            <br>
            <table class="table">
                <tr>
                    <th>
                        <h5>Items: <strong>{{order.get_cart_items}}</strong></h5>
                    </th>
                    <th>
                        <h5>Total:<strong> रू{{order.get_cart_total|floatformat:2}}</strong></h5>
                    </th>
                    <th>
                        <a style="float:right; margin:5px;" class="btn btn-success"
                            href="{% url 'store:checkout' %}">Checkout</a>
                    </th>
                </tr>
            </table>
        </div>

        <br>
        <div class="box-element">
            <div class="cart-row">
                <div style="flex:2"></div>
                <div style="flex:2"><strong>Item</strong></div>
                <div style="flex:1"><strong>Price</strong></div>
                <div style="flex:1"><strong>Quantity</strong></div>
                <div style="flex:1"><strong>Total</strong></div>
            </div>

            {% for item in items %}
            <div class="cart-row">
                <div style="flex:2"><img class="row-image" src="{{item.product.imageURL}}"></div>
                <div style="flex:2">
                    <p>{{item.product.name}}</p>
                </div>
                <div style="flex:1">
                    <p> रू{{item.product.price|floatformat:2}}</p>
                </div>
                <div style="flex:1">
                    <p class="quantity">x{{item.quantity}}</p>
                    <div class="quantity">
                        <img data-product={{item.product.id}} data-action="add" class="chg-quantity update-cart"
                            src="{% static  'images/arrow-up.png' %}">

                        <img data-product={{item.product.id}} data-action="remove" class="chg-quantity update-cart"
                            src="{% static  'images/arrow-down.png' %}">
                    </div>
                </div>
                <div style="flex:1">
                    <p> रू{{item.get_total|floatformat:2}}</p>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>{% endblock content %}

store/templates/store/main.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
    <title>
        Repeat Commerce
    </title>

    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1" />

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">

    <script type="text/javascript">
        var user = '{{request.user}}'

        function getToken(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i < cookies.length; i++) {
                    var cookie = cookies[i].trim();
                    if (cookie.substring(0, name.length + 1) === (
                        name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(
                            name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        var csrftoken = getToken('csrftoken');

        function getCookie(name) {
            // Split cookie string and get all individual name=value pairs in an array
            var cookieArr = document.cookie.split(";");

            // Loop through the array elements
            for (var i = 0; i < cookieArr.length; i++) {
                var cookiePair = cookieArr[i].split("=");

                /* Removing whitespace at the beginning of the cookie name
                and compate it with the given string */
                if (name == cookiePair[0].trim()) {
                    //Decode the cookie value and return
                    return decodeURIComponent(cookiePair[1]);
                }
            }
            // Return null if not found
            return null;
        }
        var cart = JSON.parse(getCookie('cart'))
        // creating a cart for any kind of user
        // wherther we have a cart or not
        // authenticated or unauthenticated
        // we want to have a cart for any kind of user
        if (cart == undefined) {    //if cart is undefined
            cart = {}
            console.log('Cart was created!')
            // In order to create the actual cookies, we set the object,
            // we actually want to set it to our browsers cookies
            // so to do this, we are going to do - document.cookie
            // and to set the cookie name we are going to set the string- 'cart'
            // and to set the value we are going to do equals - =
            // - 'cart='
            // we want to concatinate the values so we'll do - +
            // in theory we could do just cart
            // but because this is a cookie right now, 
            // the value needs to be a single value and it can't be an object
            // we want to turn this to a string
            // and then later on we will parse it
            // so we're going to say JSON.stringify(cart)
            // we also need to make sure that this keyValuePair is set to a single domain
            // so need to assign the cookie to the main domain of the website
            document.cookie = 'cart=' + JSON.stringify(cart) + ";domain=;path=/"
        }
        console.log('Cart:', cart)
    </script>


</head>

<body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark main-container">
        <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-repeat"
            viewBox="0 0 16 16">
            <path
                d="M11 5.466V4H5a4 4 0 0 0-3.584 5.777.5.5 0 1 1-.896.446A5 5 0 0 1 5 3h6V1.534a.25.25 0 0 1 .41-.192l2.36 1.966c.12.1.12.284 0 .384l-2.36 1.966a.25.25 0 0 1-.41-.192Zm3.81.086a.5.5 0 0 1 .67.225A5 5 0 0 1 11 13H5v1.466a.25.25 0 0 1-.41.192l-2.36-1.966a.25.25 0 0 1 0-.384l2.36-1.966a.25.25 0 0 1 .41.192V12h6a4 4 0 0 0 3.585-5.777.5.5 0 0 1 .225-.67Z" />
        </svg>
        <a class="navbar-brand" href="{% url 'store:store' %}">
            <h1>Commerce</h1>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
            <!-- <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'store:store' %}">Store <span class="sr-only">(current)</span></a>
                </li>
            </ul> -->
            <form method="GET" action="{% url 'store:store' %}">
                <div class="d-flex">
                    <input class="form-control" name="q" placeholder="Search for products..." />
                    <svg class="ml-3" version="1.1" xmlns="http://www.w3.org/2000/svg" width="50" height="32"
                        viewBox="0 0 50 32">
                        <title>search</title>
                        <path
                            d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z">
                        </path>
                    </svg>
            </form>
        </div>

        <div class="form-inline my-2 my-lg-0">
            {% if not user.is_authenticated %}
            <a href="{% url 'store:login' %}" class="btn btn-normal">
                <p>Login</p>
            </a>
            <hr>
            {% else %}
            <div class="btn btn">
                <a href="{% url 'store:user-profile' user.id %}">
                    <div class="avatar avatar--medium active">
                        {% if request.user.customer.profile_pic%}
                        <img src="{{request.user.customer.profile_pic.url}}" />
                        {% endif %}
                    </div>
                    <p style="color: black;"><b>{{request.user.username}}</b></p>
                </a>
            </div><br><br>

            <a href="{% url 'store:logout' %}" class="btn btn-normal">Logout</a>
            {% endif %}
            <div class="justify-content-end">
                <a href="{% url 'store:cart' %}">
                    <img id="cart-icon" src="{% static 'images/cart.png' %}">
                </a>
            </div>
            <p id="cart-total">{{cartItems}}</p>

    </nav>
    {% if request.user.is_superuser or request.user.is_staff %}


    <button type="button" class="btn btn-secondary btn-lg btn-block"><a href="{% url 'store:adminDashboard2' %}">Admin
            Dashboard</a></button>


    <p style="color: black;"><b></b></p>
    </a>
    {% endif %}

    <div class="main-container">
        {% block content %}

        {% endblock content %}
    </div>


    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>

    <script type="text/javascript" src="{% static 'js/cart.js' %}"></script>


</body>

</html>

store/templates/store/make_staff.html
{% extends 'store/main.html' %}

{% block content %}
<h1>Make Staff</h1>
<form method="POST" action="{% url 'store:make-staff' %}">
    {% csrf_token %}
    <div class="form-group">
        <label for="users">Select users:</label>
        <select class="form-control" id="users" name="users" multiple>
            {% for user in users %}
            <option value="{{ user.id }}">{{ user.username }}</option>
            {% endfor %}
        </select>
    </div>
    <button type="submit" class="btn btn-primary">Make Staff</button>
</form>
{% if success %}
<p>Users have been successfully made staff.</p>
{% endif %}
{% endblock %}

store/templates/store/product.html
{% extends 'store/main.html' %}
{% load static %}
{% block content %}


<div class="product-detail-image">
    <img src="{{product.imageURL}}">
</div>



<div class="col-lg-9">
    <nav id="navbar-example2" class="navbar navbar-light bg-light">
        <a class="navbar-brand" href="#">{{product.name}}</a>
        <ul class="nav nav-pills">
            <li class="nav-item">
                <a class="nav-link" href="#fat">Product Details</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">
                    <div class="spinner-border text-warning" role="status">
                        <span class="sr-only">Loading...</span>
                    </div>
                </a>
            </li>

        </ul>
    </nav>
    <div data-spy="scroll" data-target="#navbar-example2" data-offset="0">
        <p>{{product.description|safe}}</p>
    </div>
    <br>
    <hr>
    <button data-product="{{product.id}}" data-action="add" class="btn btn-outline-secondary add-btn update-cart">Add to
        Cart</button>
    {% if request.user.is_authenticated and request.user.is_superuser %}
    <a href="{% url 'store:deleteProduct' product.id %}" class="btn btn-primary">Delete
        Product</a>
    {% endif %}
    <h4 style="display: inline-block;float: right"> रू{{product.price|floatformat:2}}</h4>
</div>

{% endblock content %}

store/templates/store/profile.html
{% extends 'store/main.html' %}

{% block content %}

{% load static %}

<main class="profile-page layout layout--3">
    <div class="container">
        <div class="roomList">
            <div class="profile">
                <div class="profile__avatar">
                </div>
                <div class="profile__info">

                    <div class="jumbotron jumbotron-fluid">
                        <div class="container">
                            <h1 class="display-4">Welcome to your profile page..</h1>
                            <p class="lead">You can view your details here</p>
                            {% if request.user.customer.profile_pic%}
                            <img class="profile-pic" src="{{request.user.customer.profile_pic.url}}" />
                            {% endif %} <br> <br>
                            <h4><button type="button" class="btn btn-outline-dark"><b>Name :
                                        {{request.user.customer.name}}</b></button>
                                <br>
                                <h4><button type="button" class="btn btn-outline-dark"><b>Email :
                                            {{request.user.username}}</b></button>
                                    <br>
                                </h4>
                                <a href="{% url 'store:update-user' request.user.customer.id %}" class="btn btn-primary">Edit
                                    Profile</a>
                                <a href="{% url 'store:deleteUser' request.user.customer.id %}" class="btn btn-primary">Delete
                                    Profile</a>
                        </div>

                    </div>
                    <div>
                        <h4><button type="button" class="btn btn"><b>Check your order history here
                                    :</b></button> <br></h4>

                        <div class="row">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th scope="col">S N</th>
                                        <th scope="col">Product Name</th>
                                        <th scope="col">Date</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for orderDetail in orderDetails %}
                                    <tr>
                                        <th scope="row">{{forloop.counter}}</th>
                                        <td>
                                            <h4><button type="button"
                                                    class="btn btn-outline-dark"><b>{{orderDetail.product}}</b></button>
                                                <br>
                                            </h4>
                                        </td>
                                        <td>{{orderDetail.date_added}}</td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>

                        </div>

                        <div>
                        </div>
                    </div>
                </div>

            </div>

        </div>
    </div>
    </div>
</main>
{% endblock content %}