NBA/urls.py
from django.urls import path
from .views import (
    PlayerList,
    PlayerDetail,
    BasketballPlayerList,
    BasketballPlayerDetail,
    NBAPlayerList,
    NBAPlayerDetail,
)

urlpatterns = [
    path('players/', PlayerList.as_view(), name='player-list'),
    path('players/<int:pk>/', PlayerDetail.as_view(), name='player-detail'),
    path('basketball-players/', BasketballPlayerList.as_view(), name='basketballplayer-list'),
    path('basketball-players/<int:pk>/', BasketballPlayerDetail.as_view(), name='basketballplayer-detail'),
    path('nba-players/', NBAPlayerList.as_view(), name='nbaplayer-list'),
    path('nba-players/<int:pk>/', NBAPlayerDetail.as_view(), name='nbaplayer-detail'),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include

# urls configuration for images
from django.conf.urls.static import static
from django.conf import settings

# for JWT 
# from rest_framework_simplejwt.views import (
#     TokenObtainPairView,
#     TokenRefreshView
# )
# from rest_framework_simplejwt import views as jwt_views

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', include('api.urls')),

    path('', include('apiJWT.urls')),

    path('', include('NBA.urls')),
    
    path('', include('store.urls')),
    
    path('randomObject/', include('randomObject.urls')),

    path('ckeditor/', include('ckeditor_uploader.urls')),

    # path('api/token/',TokenObtainPairView.as_view(),name='token_object_pair'),
    # path('api/token/refresh/',TokenRefreshView.as_view(),name='token_refresh'),
]

# urls configuration for images
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

randomObject/urls.py
from django.urls import path, include

from .views import RandomObjectListView,RandomObjectDetailView,RandomObjectCreateView,RandomObjectUpdateView,RandomObjectDeleteView

app_name='randomObject'


urlpatterns = [

    path('store/', include('store.urls')),

    path('randomObject/list/', RandomObjectListView.as_view(), name='randomObject-list'),

    path('randomObject/detail/<int:pk>/', RandomObjectDetailView.as_view(), name='randomObject-detail'),

    path('randomObject/create/', RandomObjectCreateView.as_view(), name='randomObject-create'),

    path('randomObject/update/<int:pk>/', RandomObjectUpdateView.as_view(), name='randomObject-update'),

    path('randomObject/delete/<int:pk>/', RandomObjectDeleteView.as_view(), name='randomObject-delete'),

]

store/urls.py
from django.urls import path
from . import views
# from store.views import registerPage, verify_email

app_name='store'


urlpatterns = [
    path('', views.store, name="store"),

    # to make staff

    path('make-staff/', views.make_users_staff, name='make-staff'),

    # for email verification

    # path('verify-email/<int:user_id>/<str:token>/', views.verify_email, name='verify_email'),


# for admin dashboard

    # path('adminDashboard2/', views.AboutView.as_view(), name="adminDashboard2"),

    path('adminDashboard2/', views.adminDashboard, name="adminDashboard2"),


    path('adminPage/', views.adminPage, name="adminPage"),


# for user
    path('login/', views.loginPage, name="login"),
    path('logout/', views.logoutUser, name="logout"),
    path('register/', views.registerPage, name="register"),

    # path('verify_email/<int:user_id>/<str:token>/', verify_email, name='verify_email'),

    path('profile<int:pk>/', views.userProfile, name="user-profile"),
    path('update-user/<int:pk>/', views.updateUser, name="update-user"),
    path('deleteUser/<str:pk>/', views.deleteUser, name="deleteUser"),



    path('product/<int:pk>', views.ProductPage.as_view(), name="productPage"),  #.as_view() 

# CRUD for product

    path('createProduct/', views.createProduct, name="createProduct"),
    path('updateProduct/<str:pk>/', views.updateProduct,name="updateProduct"),
    path('deleteProduct/<str:pk>/', views.deleteProduct, name="deleteProduct"),

# Cart and Checkout views

    path('cart/', views.cart, name="cart"),
    path('checkout/', views.checkout, name="checkout"),

    path('update_item/', views.updateItem, name="update_item"),
    
    path('process_order/', views.processOrder, name="process_order"),
]
 

randomObject/models.py
from django.db import models

class RandomObject(models.Model):
    name = models.CharField(max_length=200)
    type = models.CharField(max_length=30)

    def __str__(self):
        return self.name

randomObject/views.py
from django.shortcuts import render
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView
from django.urls import reverse_lazy
from .models import RandomObject

# RandomObject list view
class RandomObjectListView(ListView):
    model = RandomObject
    template_name = 'randomObject/randomObject_list.html'
    # context_object_name = 'randomObject:randomObjects'

# RandomObject detail view
class RandomObjectDetailView(DetailView):
    model = RandomObject
    template_name = 'randomObject/randomObject_detail.html'
    context_object_name = 'randomObject:randomObject'

# RandomObject create view
class RandomObjectCreateView(CreateView):
    model = RandomObject
    fields = ['name', 'type']
    template_name = 'randomObject/randomObject_create.html'
    success_url = reverse_lazy('store:adminDashboard2')

# RandomObject update view
class RandomObjectUpdateView(UpdateView):
    model = RandomObject
    fields = ['name', 'type']
    template_name = 'randomObject/randomObject_update.html'
    success_url = reverse_lazy('store:adminDashboard2')

# RandomObject delete view
class RandomObjectDeleteView(DeleteView):
    model = RandomObject
    template_name = 'randomObject/randomObject_delete.html'
    success_url = reverse_lazy('store:adminDashboard2')

randomObject/templates/randomObject/base.html
<!DOCTYPE html>
<html>

<head>
    <title>RandomObject</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>

<body>
    <header>
        <nav>
            <ul class="nav justify-content-center">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'randomObject:randomObject-list' %}">
                        <h1><span class="badge badge-secondary">Random Object</span></h1>
                    </a>
                </li>
            </ul>
        </nav>
    </header>

    <main>
        {% block content %}
        {% endblock %}
    </main>

    <footer>
        <!-- Add your footer content here -->
    </footer>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
</body>

</html>

randomObject/templates/randomObject/randomObject_create.html
{% extends 'randomObject/base.html' %}

{% block content %}
<h1>Create a Random Object which a staff cannot see!!</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Create</button>
</form>
<a href="{% url 'store:adminDashboard2' %}">Back to random object list</a>
{% endblock %}

randomObject/templates/randomObject/randomObject_delete.html
{% extends 'randomObject/base.html' %}

{% block content %}
<h1>Delete {{ object.name }}?</h1>
<form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete this random object which a staff can't see?</p>
    <button type="submit">Yes</button>
    <a href="{% url 'store:adminDashboard2' %}">No, cancel</a>
</form>
{% endblock %}

randomObject/templates/randomObject/randomObject_detail.html
{% extends 'randomObject/base.html' %}

{% block content %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'randomObject:randomObject-list' %}">RandomObject List</a></li>
        <li class="breadcrumb-item active" aria-current="page">{{ randomObject.name }}</li>
    </ol>
</nav>

<h1>{{ randomObject.name }}</h1>
<p>Type: {{ randomObject.type }}</p>

<a href="{% url 'randomObject:randomObject-update' randomObject.id %}" class="btn btn-secondary">Update</a>
<a href="{% url 'randomObject:randomObject-delete' randomObject.id %}" class="btn btn-danger">Delete</a>

{% endblock %}

randomObject/templates/randomObject/randomObject_list.html
{% extends 'randomObject/base.html' %}


{% block content %}
<div class="alert alert-success" role="alert">
    <h4 class="alert-heading">Hello there !</h4>
    <p>Welcome to the Random Obj CRUD page ! </p>
    <hr>
    <p class="mb-0">Here, you can view the random objects in the system, update and delete the random objs and also
        create new random objs.</p>
</div>
<table class="table table-dark">
    <thead>
        <tr>
            <th scope="col">S N</th>
            <th scope="col">Random Object Name</th>
        </tr>
    </thead>
    <tbody>
        {% for randomObject in object_list %}
        <tr>
            <th scope="row">1</th>
            <td><a
                    href="{% url 'randomObject:randomObject-detail' pk=randomObject.pk %}">{{randomObject.name}}</a>
            </td>
            <td><a href="{% url 'randomObject:randomObject-update' pk=randomObject.pk %}"
                    class="btn btn-secondary btn-lg" role="button">Update</a>
            </td>
            <td><a href="{% url 'randomObject:randomObject-delete' pk=randomObject.pk %}" class="btn btn-danger btn-lg"
                    role="button">Delete</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>

</table>
<div class="jumbotron">
    <a class="btn btn-primary btn-lg" href="{% url 'randomObject:randomObject-create' %}" role="button">Create a new
        random object</a>
</div>

{% endblock %}

randomObject/templates/randomObject/randomObject_update.html
{% extends 'randomObject/base.html' %}

{% block content %}
<h1>Edit {{ object.name }}</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Update</button>
</form>
<a href="{% url 'store:adminDashboard2' %}">Back to random object list</a>
{% endblock %}